### ISSUE TITLE
problem: cannot use the app

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/nostrocket-ui#2]
problem: cannot use the app

possible solution:
use a build script that can be executed whenever pushing a commit, this would put a compiled static version of the code in some directory or in a branch that we can then use to serve github pages

**Comment by samuelralak** [comment]
@gazhayes there's a build script [here](https://github.com/nostrocket/nostrocket-ui/blob/main/.github/workflows/deploy.yml) which auto deploys to Github pages whenever a pull request or a commit is made to the `main` branch. The deployment can be found [here](https://nostrocket.github.io/nostrocket-ui/)

Not entirely certain if my response resolves the issue  so please correct me if its referring to something else.
